In [52]:
from sklearn.ensemble import AdaBoostClassifier
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [53]:
train_dataset = np.loadtxt(open('fs/train_fs.csv'), delimiter=',', dtype=np.float32, skiprows=1)
train_labels = np.loadtxt(open('fs/train_labels.csv'), delimiter=',', dtype=np.float32, skiprows=1)
test_dataset = np.loadtxt(open('fs/test_fs.csv'), delimiter=',', dtype=np.float32, skiprows=1)
test_labels = np.loadtxt(open('fs/test_labels.csv'), delimiter=',', dtype=np.float32, skiprows=1)

In [58]:
clf = AdaBoostClassifier(n_estimators=120)
clf.fit(train_dataset, train_labels)
preds1 = clf.predict(train_dataset)
print (accuracy_score(train_labels, preds1))
print (confusion_matrix(train_labels, preds1))
print (classification_report(train_labels, preds1))
preds2 = clf.predict(test_dataset)
print (accuracy_score(test_labels, preds2))
print (confusion_matrix(test_labels, preds2))
print (classification_report(test_labels, preds2))

0.999002064694
[[ 97086    191]
 [   302 396441]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     97277
        1.0       1.00      1.00      1.00    396743

avg / total       1.00      1.00      1.00    494020

0.921708013426
[[ 59629    963]
 [ 23388 227048]]
             precision    recall  f1-score   support

        0.0       0.72      0.98      0.83     60592
        1.0       1.00      0.91      0.95    250436

avg / total       0.94      0.92      0.93    311028



In [55]:
clf = RandomForestClassifier(max_depth=7, n_estimators=200, n_jobs=4)
clf.fit(train_dataset, train_labels)
preds1 = clf.predict(train_dataset)
print (accuracy_score(train_labels, preds1))
print (confusion_matrix(train_labels, preds1))
print (classification_report(train_labels, preds1))
preds2 = clf.predict(test_dataset)
print (accuracy_score(test_labels, preds2))
print (confusion_matrix(test_labels, preds2))
print (classification_report(test_labels, preds2))

0.999277357192
[[ 97269      8]
 [   349 396394]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     97277
        1.0       1.00      1.00      1.00    396743

avg / total       1.00      1.00      1.00    494020

0.923026222719
[[ 60344    248]
 [ 23693 226743]]
             precision    recall  f1-score   support

        0.0       0.72      1.00      0.83     60592
        1.0       1.00      0.91      0.95    250436

avg / total       0.94      0.92      0.93    311028



In [57]:
clf = LogisticRegression(n_jobs=-1)
clf.fit(train_dataset, train_labels)
preds1 = clf.predict(train_dataset)
print (accuracy_score(train_labels, preds1))
print (confusion_matrix(train_labels, preds1))
print (classification_report(train_labels, preds1))
preds2 = clf.predict(test_dataset)
print (accuracy_score(test_labels, preds2))
print (confusion_matrix(test_labels, preds2))
print (classification_report(test_labels, preds2))

0.992352536335
[[ 96160   1117]
 [  2661 394082]]
             precision    recall  f1-score   support

        0.0       0.97      0.99      0.98     97277
        1.0       1.00      0.99      1.00    396743

avg / total       0.99      0.99      0.99    494020

0.919306300397
[[ 59615    977]
 [ 24121 226315]]
             precision    recall  f1-score   support

        0.0       0.71      0.98      0.83     60592
        1.0       1.00      0.90      0.95    250436

avg / total       0.94      0.92      0.92    311028

